import React from 'react'
import PricingManagementInteractive from './PricingManagementInteractive';

export default function Pricing() {

    const mockPricingData = [
        {
            id: 1,
            serviceName: 'Cardiology Consultation',
            serviceCode: 'CPT-99213',
            category: 'Cardiology',
            basePrice: 250,
            insuranceRate: 200,
            discount: 10,
            effectiveDate: '2025-01-01',
            expiryDate: '2025-12-31',
            status: 'Active',
            taxRate: 8.5,
            notes: 'Standard consultation rate for cardiology department',
        },
        {
            id: 2,
            serviceName: 'MRI Scan - Brain',
            serviceCode: 'CPT-70553',
            category: 'Diagnostic Imaging',
            basePrice: 1200,
            insuranceRate: 950,
            discount: 5,
            effectiveDate: '2025-01-01',
            expiryDate: '2025-12-31',
            status: 'Active',
            taxRate: 8.5,
            notes: 'Brain MRI with contrast',
        },
        {
            id: 3,
            serviceName: 'Emergency Room Visit',
            serviceCode: 'CPT-99285',
            category: 'Emergency Care',
            basePrice: 850,
            insuranceRate: 700,
            discount: 0,
            effectiveDate: '2025-01-01',
            expiryDate: '2025-12-31',
            status: 'Active',
            taxRate: 8.5,
            notes: 'Level 5 emergency room visit',
        },
        {
            id: 4,
            serviceName: 'Complete Blood Count',
            serviceCode: 'CPT-85025',
            category: 'Laboratory Tests',
            basePrice: 45,
            insuranceRate: 35,
            discount: 15,
            effectiveDate: '2025-01-15',
            expiryDate: '2025-12-31',
            status: 'Pending',
            taxRate: 8.5,
            notes: 'Automated CBC with differential',
        },
        {
            id: 5,
            serviceName: 'Physical Therapy Session',
            serviceCode: 'CPT-97110',
            category: 'Rehabilitation',
            basePrice: 120,
            insuranceRate: 95,
            discount: 20,
            effectiveDate: '2024-01-01',
            expiryDate: '2024-12-31',
            status: 'Expired',
            taxRate: 8.5,
            notes: 'Therapeutic exercises, 30 minutes',
        },
        {
            id: 6,
            serviceName: 'X-Ray - Chest',
            serviceCode: 'CPT-71046',
            category: 'Diagnostic Imaging',
            basePrice: 180,
            insuranceRate: 145,
            discount: 8,
            effectiveDate: '2025-01-01',
            expiryDate: '2025-12-31',
            status: 'Active',
            taxRate: 8.5,
            notes: 'Two-view chest X-ray',
        },
        {
            id: 7,
            serviceName: 'Ultrasound - Abdominal',
            serviceCode: 'CPT-76700',
            category: 'Diagnostic Imaging',
            basePrice: 350,
            insuranceRate: 280,
            discount: 12,
            effectiveDate: '2025-02-01',
            expiryDate: '2025-12-31',
            status: 'Pending',
            taxRate: 8.5,
            notes: 'Complete abdominal ultrasound',
        },
        {
            id: 8,
            serviceName: 'Surgical Consultation',
            serviceCode: 'CPT-99243',
            category: 'Surgery',
            basePrice: 300,
            insuranceRate: 240,
            discount: 5,
            effectiveDate: '2025-01-01',
            expiryDate: '2025-12-31',
            status: 'Active',
            taxRate: 8.5,
            notes: 'Pre-operative surgical consultation',
        },
    ];

    const mockAnalyticsData = {
        revenueData: [
            { month: 'Jan', projected: 125000, actual: 118000 },
            { month: 'Feb', projected: 135000, actual: 142000 },
            { month: 'Mar', projected: 145000, actual: 138000 },
            { month: 'Apr', projected: 155000, actual: 162000 },
            { month: 'May', projected: 165000, actual: 171000 },
            { month: 'Jun', projected: 175000, actual: 168000 },
        ],
        utilizationData: [
            { service: 'Cardiology', utilization: 85 },
            { service: 'MRI', utilization: 72 },
            { service: 'Emergency', utilization: 95 },
            { service: 'Lab Tests', utilization: 88 },
            { service: 'Physical Therapy', utilization: 65 },
        ],
        competitiveData: [
            { service: 'Cardiology Consult', ourPrice: 250, marketAvg: 275 },
            { service: 'MRI Scan', ourPrice: 1200, marketAvg: 1350 },
            { service: 'ER Visit', ourPrice: 850, marketAvg: 900 },
            { service: 'Blood Test', ourPrice: 45, marketAvg: 55 },
            { service: 'X-Ray', ourPrice: 180, marketAvg: 200 },
        ],
    };

    const mockHistoryData = [
        {
            id: 1,
            action: 'Updated',
            date: '12/06/2025 02:30 PM',
            basePrice: 250,
            insuranceRate: 200,
            discount: 10,
            status: 'Active',
            modifiedBy: 'Dr. Sarah Johnson',
            notes: 'Updated pricing based on market analysis',
            changes: ['Base price increased from $230 to $250', 'Discount adjusted from 5% to 10%'],
        },
        {
            id: 2,
            action: 'Updated',
            date: '11/15/2025 10:15 AM',
            basePrice: 230,
            insuranceRate: 185,
            discount: 5,
            status: 'Active',
            modifiedBy: 'Admin User',
            notes: 'Quarterly pricing review',
            changes: ['Insurance rate updated to match new contracts'],
        },
        {
            id: 3,
            action: 'Created',
            date: '01/01/2025 09:00 AM',
            basePrice: 220,
            insuranceRate: 180,
            discount: 0,
            status: 'Active',
            modifiedBy: 'System Admin',
            notes: 'Initial pricing tier setup',
            changes: [],
        },
    ];

    const mockNotifications = [
        {
            id: 1,
            title: 'Pending Approval',
            message: '3 new pricing tiers require approval',
            type: 'warning',
            read: false,
            timestamp: '2025-12-06T18:30:00',
        },
        {
            id: 2,
            title: 'Pricing Update',
            message: 'Cardiology consultation rates updated',
            type: 'info',
            read: false,
            timestamp: '2025-12-06T17:45:00',
        },
        {
            id: 3,
            title: 'System Alert',
            message: 'Billing integration sync completed',
            type: 'success',
            read: true,
            timestamp: '2025-12-06T16:20:00',
        },
    ];

    const initialData = {
        pricingData: mockPricingData,
        analyticsData: mockAnalyticsData,
        historyData: mockHistoryData,
        notifications: mockNotifications,
    };


    return (
        <PricingManagementInteractive initialData={initialData} />
    )
}
